# fly.toml app configuration file generated for notes-backend-fso-adrian on 2024-12-15T16:31:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-backend-fso-adrian'
primary_region = 'otp'

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
